from pathlib import Path

NOTES = {
"01_cover": "Good afternoon, professor and classmates. Our group proposes a three-hour-ahead temperature forecast on an FPGA using a linear model built from past values. This is a focused version of the assigned weather forecasting topic. Today we present the proposed method and twelve-week plan; we do not yet have fitted coefficients, accuracy results, or a board demonstration.",
"02_scope": "We narrow the broad weather forecasting topic to hourly temperature at one location. At time t, the model uses observations available up to t and outputs a forecast for t plus three hours, in degrees Celsius. A linear model gives us clear arithmetic that we can reproduce in C++ and RTL within three months. FPGA speedup is not our claim for data that arrives only once an hour; our objective is the complete model-to-hardware workflow.",
"03_system": "The system has an offline stage and an FPGA runtime stage. C++ checks the CSV data, builds simple baselines, fits coefficients a, b, and c, and creates a fixed-point reference and test vectors. The FPGA receives temperature samples, stores the required history, and computes the forecast with coefficients fixed at runtime. Our deliverables are the C++ program, RTL, testbench, board demo, and an evaluation report.",
"04_samples": "We plan to use hourly NASA POWER T2M data, which is gridded data for a selected coordinate rather than a sensor reading at an exact point. We will confirm the coordinate, date range, time convention, units, and any missing or duplicate hours before creating samples. The value at t minus twenty-one hours is the same hour on the previous day relative to the target at t plus three hours. A buffer of twenty-five consecutive samples covers t minus twenty-four through t; the future target is used only as a training or evaluation label.",
"05_model": "The forecast starts from the temperature at the same hour on the previous day relative to the target. One correction uses the difference between the current hour and the same hour a day earlier; another uses the change over the latest three hours. C++ will estimate the two weights and constant offset from historical data, and the FPGA will use those fixed values. The model is a hypothesis that still needs comparison against baselines on unseen data.",
"06_example": "This is an invented arithmetic example, not an experimental result. With past temperatures of nineteen, twenty-one, eighteen, and twenty degrees Celsius and example coefficients a equal to zero point five, b equal to zero point two, and c equal to zero, the forecast is twenty-one point nine degrees Celsius. The hardware therefore needs subtraction, multiplication by coefficients, and addition. A correct computation does not by itself establish forecast accuracy.",
"07_training": "We rewrite the model as a small linear regression problem: x one is the day-to-day difference, x two is the recent three-hour difference, and y is the target temperature minus the same-hour anchor. C++ fits a, b, and c by least squares on training data. We divide data chronologically into training, validation, and test periods; training labels must not extend into later periods. Previously observed history may still be used as input when forecasting in a later period.",
"08_evaluation": "Our first question is whether the forecast improves on simple alternatives: the current temperature and the same-hour value from the previous day. We will compare all methods on the same test timestamps using mean absolute error in degrees Celsius. Our second question is whether the hardware follows its specification: we compare floating point with fixed point, then require RTL to match the fixed-point reference bit for bit at the correct valid cycle. LUT, flip-flop, DSP, and latency figures will come from synthesis rather than estimates.",
"09_fixed_point": "We will start with a floating-point C++ model and inspect the ranges of temperatures, fitted coefficients, products, and sums before choosing a fixed-point format. The specification must include signedness, fractional bits, intermediate widths, shifts, rounding, and overflow behavior. A C++ fixed-point reference will mirror the RTL operation by operation, including width reductions. Forecast error against measured temperature and fixed-point error against the floating-point model are different quantities.",
"10_architecture": "The FPGA accepts a new sample only when valid is asserted. It stores twenty-five samples so it can read the four required time indices, forms two differences, multiplies them by the fixed coefficients, and adds the anchor and offset. The diagram describes functions, not a final choice between shared and parallel multipliers. A delay of one sample represents one hour in the data sequence, whereas hardware latency is measured in clock cycles; the circuit does not wait three real hours to forecast.",
"11_verification": "We propose three layers of verification using the same input vectors. C++ compares floating-point and fixed-point calculations, especially at negative values and numeric limits. The testbench checks bit-exact RTL outputs at the expected valid cycle and covers reset, overflow, buffer warm-up, and gaps between accepted samples. The board run checks sample order, data encoding, interface behavior, and output logs against the reference.",
"12_demo": "The proposed demonstration replays historical data from a PC into the FPGA in chronological order, faster than real time. UART is one possible interface, depending on the available board. The PC logs the returned forecasts and compares each one with the target temperature in the CSV. At each forecast step, only samples through time t enter the FPGA; the future label remains on the PC for evaluation.",
"13_schedule": "We divide twelve weeks into four stages with a working deliverable at each milestone. Weeks one to three cover foundations, clean data, and two baselines; weeks four to six cover C++ training, validation, and initial fixed-point analysis. Weeks seven to nine cover RTL and bit-exact testbench checks, while preparing board integration. The final three weeks cover the demo, held-out test evaluation, synthesis figures, and limitations.",
"14_team_risks": "One student leads data and C++, another leads fixed-point RTL, and the third leads verification and the demonstration. The group must agree early on data formats, coefficient encoding, signed arithmetic, rounding, overflow, valid, and latency. Missing or misaligned hours are checked before sample creation; if the board is undecided, we can still complete and simulate a standalone core. If forecast error is high, we will analyze it on validation and report the held-out test result honestly.",
"15_conclusion": "Our proposed outcome is a three-hour-ahead temperature forecast from past hourly values, with coefficients trained in C++ and fixed-point inference on an FPGA. We will provide two kinds of evidence: forecast quality against baselines on unseen data, and RTL correctness against the fixed-point reference. We would welcome feedback on the three-hour scope, the FPGA board and tools, and the minimum expected board demonstration. Humidity or pressure would be added only after the core work is complete.",
}

root = Path(__file__).parent / 'notes'
root.mkdir(exist_ok=True)
for name, body in NOTES.items():
    (root / f'{name}.md').write_text(body + '\n', encoding='utf-8')
(root / 'total.md').write_text('\n\n---\n\n'.join(f'# {name}\n\n{body}' for name, body in NOTES.items()) + '\n', encoding='utf-8')
print(f'Wrote {len(NOTES)} English speaker notes')
